#!/bin/bash
./myDCT tests/0/test0.pgm ./quantfile 1.0 outTest0
./myDCT tests/1/test1.pgm ./quantfile 1.0 outTest1
./myDCT tests/2/test2.pgm ./quantfile 1.0 outTest2
./myDCT tests/2/test2.pgm ./quantfile 3.5 outTest35

./myIDCT tests/0/test0.1.0.dct ./quantfile outTest0IDCT.pgm
./myIDCT tests/1/test1.1.0.dct ./quantfile outTest1IDCT.pgm
./myIDCT tests/2/test2.1.0.dct ./quantfile outTest2IDCT.pgm
./myIDCT tests/2/test2.3.5.dct ./quantfile outTest23_5IDCT.pgm
